import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ModuleItem } from '../../../../models/module.model';
import { ModuleService } from '../../../../services/module.service';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-addnew',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './addnew.component.html',
  styleUrl: './addnew.component.css'
})
export class AddnewComponent {
  newModule: ModuleItem = {
    id: 0, // id will typically be auto-generated by the server
    module_name: '',
    description: ''
  };

  constructor(private moduleService: ModuleService, private router: Router) { }

  addModule() {
    this.moduleService.addModule(this.newModule).subscribe({
      next: (module) => {
        console.log('Module added successfully', module);
        this.router.navigate(['/home/module']); // Navigate back to the module list page
      },
      error: (error) => {
        console.error('Error adding module', error);
      }
    });
  }
}

